.

diff --git a/whonix_shared/usr/lib/whonix/uwtwrapper b/whonix_shared/usr/lib/whonix/uwtwrapper
--- a/whonix_shared/usr/lib/whonix/uwtwrapper
+++ b/whonix_shared/usr/lib/whonix/uwtwrapper
@@ -35,12 +35,12 @@ exit 1
 trap "error_handler" ERR
 
 sanity_tests_general() {
-   if [ ! -e "/usr/bin/$SCRIPTNAME.real" ]; then
-      echo "$SCRIPTNAME uwt wrapper ERROR: /usr/bin/$SCRIPTNAME.real does not exist."
+   if [ ! -e "/usr/bin/$SCRIPTNAME.whonix-orig" ]; then
+      echo "$SCRIPTNAME uwt wrapper ERROR: /usr/bin/$SCRIPTNAME.whonix-orig does not exist."
       exit 1
    fi
-   if [ ! -x "/usr/bin/$SCRIPTNAME.real" ]; then
-      echo "$SCRIPTNAME uwt wrapper ERROR: /usr/bin/$SCRIPTNAME.real is not executable."
+   if [ ! -x "/usr/bin/$SCRIPTNAME.whonix-orig" ]; then
+      echo "$SCRIPTNAME uwt wrapper ERROR: /usr/bin/$SCRIPTNAME.whonix-orig is not executable."
       exit 1
    fi
 }
@@ -125,27 +125,27 @@ else
    fi
 fi
 
-## Using "|| { ret="$?" ; true; };" to prevent invoking error_handler in case
-## the executed application returned a non-zero value.
+## Using "|| { exit_code="$?" ; true; };" to prevent invoking error_handler in case
+## the executed application exits with a non-zero value.
 ##
 ## Bash syntax: command1 || command2
 ##
-## Setting default ret="0" beforehand, because
-## command2 does only get executed, if command1 return non-zero.
-## So in case it's zero, the default return value must be already set.
+## Setting default exit_code="0" beforehand, because
+## command2 does only get executed, if command1 exits non-zero.
+## So in case it's zero, the default exit_code value must be already set.
 
 if [ "$uwtwrapper_global" = "0" ]; then
    if [ "$fake_time" = "faketime" ]; then
       sanity_tests_general
       sanity_tests_timeprivacy
-      ret="0"
-      exec "$fake_time" "$privacy_time" "/usr/bin/$SCRIPTNAME.real" ${1+"$@"} || { ret="$?" ; true; };
+      exit_code="0"
+      exec "$fake_time" "$privacy_time" "/usr/bin/$SCRIPTNAME.whonix-orig" ${1+"$@"} || { exit_code="$?" ; true; };
    else
       sanity_tests_general
-      ret="0"
-      exec "/usr/bin/$SCRIPTNAME.real" ${1+"$@"} || { ret="$?" ; true; };
+      exit_code="0"
+      exec "/usr/bin/$SCRIPTNAME.whonix-orig" ${1+"$@"} || { exit_code="$?" ; true; };
    fi
-   exit "$ret"
+   exit "$exit_code"
 fi
 
 temp="uwtwrapper_$SCRIPTNAME_CLEANED"
@@ -154,28 +154,28 @@ if [ "${!temp}" = "0" ]; then
    if [ "$fake_time" = "faketime" ]; then
       sanity_tests_general
       sanity_tests_timeprivacy
-      ret="0"
-      exec "$fake_time" "$privacy_time" "/usr/bin/$SCRIPTNAME.real" ${1+"$@"} || { ret="$?" ; true; };
+      exit_code="0"
+      exec "$fake_time" "$privacy_time" "/usr/bin/$SCRIPTNAME.whonix-orig" ${1+"$@"} || { exit_code="$?" ; true; };
    else
       sanity_tests_general
-      ret="0"
-      exec "/usr/bin/$SCRIPTNAME.real" ${1+"$@"} || { ret="$?" ; true; };
+      exit_code="0"
+      exec "/usr/bin/$SCRIPTNAME.whonix-orig" ${1+"$@"} || { exit_code="$?" ; true; };
    fi
-   exit "$ret"
+   exit "$exit_code"
 fi
 
 if [ "$fake_time" = "faketime" ]; then
    sanity_tests_general
    sanity_tests_uwt
    sanity_tests_timeprivacy
-   ret="0"
-   exec "$fake_time" "$privacy_time" "/usr/bin/uwt" -t 5 -i "$uwtwrapper_gateway_ip" -p "$port" "/usr/bin/$SCRIPTNAME.real" ${1+"$@"} || { ret="$?" ; true; };
+   exit_code="0"
+   exec "$fake_time" "$privacy_time" "/usr/bin/uwt" -t 5 -i "$uwtwrapper_gateway_ip" -p "$port" "/usr/bin/$SCRIPTNAME.whonix-orig" ${1+"$@"} || { exit_code="$?" ; true; };
 else
    sanity_tests_general
    sanity_tests_uwt
-   ret="0"
-   exec "/usr/bin/uwt" -t 5 -i "$uwtwrapper_gateway_ip" -p "$port" "/usr/bin/$SCRIPTNAME.real" ${1+"$@"} || { ret="$?" ; true; };
+   exit_code="0"
+   exec "/usr/bin/uwt" -t 5 -i "$uwtwrapper_gateway_ip" -p "$port" "/usr/bin/$SCRIPTNAME.whonix-orig" ${1+"$@"} || { exit_code="$?" ; true; };
 fi
-exit "$ret"
+exit "$exit_code"
 
 ## End of Whonix /usr/bin/$SCRIPTNAME uwt wrapper.
